-- 코드를 입력하세요
WITH TBL AS
(SELECT MEMBER_ID, COUNT(*) AS CNT 
 FROM REST_REVIEW 
 GROUP BY MEMBER_ID 
 ORDER BY 2 DESC LIMIT 1
)
SELECT A.MEMBER_NAME, B.REVIEW_TEXT, DATE_FORMAT(B.REVIEW_DATE, "%Y-%m-%d") AS REVIEW_DATE
FROM MEMBER_PROFILE A JOIN REST_REVIEW B
ON A.MEMBER_ID = B.MEMBER_ID
JOIN TBL T ON B.MEMBER_ID = T.MEMBER_ID 
ORDER BY B.REVIEW_DATE, B.REVIEW_TEXT

